'Status: Review':
- changed-files:
  - any-glob-to-any-file: '**'

'Type: Feat':
- head-branch: ['feat', 'ˆfeat']

'Type: Fix':
- head-branch: ['fix', 'ˆfix']

'Type: CI':
- head-branch: ['ci', '^ci']
